issuebot:
  triage:
    repositories:
      - organization: spring-projects
        name: spring-boot
        label: waiting-for-triage
        collaborators:
          - dsyer
          - philwebb
          - snicoll
          - wilkinsona
