casbot:
  github:
    repository:
      organization: apereo
      name: cas
      collaborators:
        - mmoayyed
        - leleuj
        - tduehr
        - tsschmidt
        - mindblender
        - hdeadman
        - dima767
        - frett
        - wgthom
