issuebot:
  github:
    repository:
      organization: spring-projects
      name: spring-boot
  triage:
    label: waiting-for-triage
    collaborators:
      - dsyer
      - philwebb
      - snicoll
      - wilkinsona
