name: CAS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialize
        run: chmod -R 777 ./ci/*.sh && ./ci/init-build.sh
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        run: chmod -R 777 ./ci/*.sh && ./ci/init-build.sh
      - uses: actions/checkout@v2
      - name: Download Dependencies
        run: chmod -R 777 ./ci/*.sh && ./ci/download-dependencies.sh
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
  build-jdk11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Initialize
      run: chmod -R 777 ./ci/*.sh && ./ci/init-build.sh
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
       java-version: 11.0.7
    - name: Build with Gradle
      run: ./gradlew --build-cache --configure-on-demand --no-daemon build install -x test -x javadoc -x check -DskipNestedConfigMetadataGen=true --parallel
